import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAccessibleDescription("")
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t1.setFont(font)
        self.t1.setObjectName("t1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.t1)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t2.setFont(font)
        self.t2.setStyleSheet("color:blue;\n"
"border:none")
        self.t2.setObjectName("t2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2)
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("border:1px solid black;\n"
"background-color:#D3D3D3")
        self.button1.setObjectName("button1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.button1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t3.setFont(font)
        self.t3.setObjectName("t3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.t3)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t4.setFont(font)
        self.t4.setStyleSheet("color:blue;\n"
"border:none")
        self.t4.setObjectName("t4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.t4)
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("border:1px solid black;\n"
"background-color:#D3D3D3")
        self.button2.setObjectName("button2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.button2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#Making the Button Work
        self.button1.clicked.connect(self.buttonevent1)
        self.button2.clicked.connect(self.buttonevent2)
        "Create Button 2 Here!!!"
    def buttonevent1(self):
            #SQL Definiton
            shelf=sqlite3.connect("bookshelf.db")
            curshelf=shelf.cursor()
            text_title=self.t1.text()
            a=curshelf.execute("SELECT * FROM shelf WHERE title='"+text_title+"';")
            try:
                b=curshelf.fetchone()
                price=(b[3])
                self.t2.setText(str(price))
            except:
                self.t2.setText("No Records Found")
    def buttonevent2(self):
            #SQL Definiton
            shelf=sqlite3.connect("bookshelf.db")
            curshelf=shelf.cursor()
            _text_title=self.t1.text()
            _a=curshelf.execute("SELECT * FROM shelf WHERE title='"+_text_title+"';")
            _b=curshelf.fetchone()
            try:
                    _quantity=int(self.t3.text())
                    self.t4.setText(str((_b[3])*_quantity))
            except:
                    self.t4.setText("Enter Quantity!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Book Title:"))
        self.t1.setPlaceholderText(_translate("MainWindow", "text"))
        self.label3.setText(_translate("MainWindow", "Price:"))
        self.t2.setText(_translate("MainWindow", "Rs. 0"))
        self.t2.setPlaceholderText(_translate("MainWindow", "text"))
        self.button1.setText(_translate("MainWindow", "Find Price"))
        self.label2.setText(_translate("MainWindow", "Quantity:"))
        self.t3.setPlaceholderText(_translate("MainWindow", "number"))
        self.label4.setText(_translate("MainWindow", "Total:"))
        self.t4.setText(_translate("MainWindow", "Rs. 0"))
        self.t4.setPlaceholderText(_translate("MainWindow", "text"))
        self.button2.setText(_translate("MainWindow", "Find Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

