# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(381, 111))
        self.lcdNumber.setMaximumSize(QtCore.QSize(381, 111))
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_3.addWidget(self.lcdNumber, 0, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_18.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_17.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_19.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_2.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_22.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_3.addWidget(self.pushButton_22, 2, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_21.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_3.addWidget(self.pushButton_21, 2, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_20.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_3.addWidget(self.pushButton_20, 2, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_25.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 3, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_24.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 3, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_23.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 3, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_4.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_28.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_3.addWidget(self.pushButton_28, 4, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_27.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_3.addWidget(self.pushButton_27, 4, 2, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setMinimumSize(QtCore.QSize(81, 41))
        self.pushButton_26.setMaximumSize(QtCore.QSize(90, 41))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_18.setText(_translate("MainWindow", "2"))
        self.pushButton_17.setText(_translate("MainWindow", "3"))
        self.pushButton_19.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "4"))
        self.pushButton_22.setText(_translate("MainWindow", "5"))
        self.pushButton_21.setText(_translate("MainWindow", "6"))
        self.pushButton_20.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "7"))
        self.pushButton_25.setText(_translate("MainWindow", "8"))
        self.pushButton_24.setText(_translate("MainWindow", "9"))
        self.pushButton_23.setText(_translate("MainWindow", "x"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))
        self.pushButton_28.setText(_translate("MainWindow", "0"))
        self.pushButton_27.setText(_translate("MainWindow", "Enter"))
        self.pushButton_26.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

